#cloud-config
write_files:
  # Set up rabbitmq users and mgmt plugin
  - path: /root/configure_rabbitmq.sh
    content: |
        #!/usr/bin/env bash
        rabbitmqctl add_user admin 'ilovebunnies'
        rabbitmqctl set_user_tags admin administrator
        rabbitmqctl add_user rabbit 'ilovebunnies'
        rabbitmqctl add_vhost /
        rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
        rabbitmqctl set_permissions -p / rabbit ".*" ".*" ".*"
        rabbitmqctl delete_user guest
        rabbitmq-plugins enable rabbitmq_management

  # Set cluster cookie
  - path: /var/lib/rabbitmq/.erlang.cookie
    content: 'THISISARABBITMQCOOKIELOL'
  
  # Testing script
  - path: /root/smoke_test.sh
    content: |
      #!/usr/bin/env bash
      curl -s -u admin:ilovebunnies -X POST -H "Content-Type: application/json" \
      -d '{"properties":{},"routing_key":"hello","payload":"hello-world","payload_encoding":"string"}' \
      http://localhost:15672/api/exchanges/%2f/amq.default/publish > /tmp/smoke_test

  - path: /etc/rabbitmq/rabbitmq-env.conf
    content: |
      HOME=/var/lib/rabbitmq
      LOG_BASE=/var/log/rabbitmq
      MNESIA_BASE=/var/lib/rabbitmq/mnesia

runcmd:
  - cp /var/lib/rabbitmq/.erlang.cookie $HOME
  - systemctl restart rabbitmq-server.service
  - sleep 10
  - bash /root/configure_rabbitmq.sh > /tmp/configure_log
  - echo "done" >> /tmp/configure_log
  - sleep 10
  - bash /root/smoke_test.sh
